// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package data

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID             int32
	Title          string
	Body           string
	PublishedOn    sql.NullTime
	BannerImageUrl sql.NullString
	AuthorID       uuid.UUID
	PorjectID      int32
	CreatedOn      time.Time
	UpdatedOn      sql.NullTime
}

type Project struct {
	ID          int32
	Name        string
	Description string
	AccentColor string
	LogoUrl     sql.NullString
	AppKey      string
	UserID      uuid.UUID
	CreatedOn   time.Time
	UpdatedOn   sql.NullTime
}
